version: '3.8'

networks:
    lux_network:
        name: lux_network
        driver: bridge

volumes:
    lux-mysql-db:
    rabbitmq_storage:

services:
    lux_api:
        image: lux_api:latest
        user: "www-data:www-data"
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                ENVIRONMENT: development
                GROUP_ID: 1000
                USER_ID: 1000
        ports:
            - "9005:9001"
        depends_on:
            - lux_db
        volumes:
            - ./:/var/www/html
        networks:
            - lux_network

    lux_db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - lux-mysql-db:/var/lib/mysql
        networks:
            - lux_network

    lux_nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "86:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        networks:
            - lux_network

    lux_adminer:
        image: adminer
        container_name: lux_adminer
        ports:
            - "8888:8080"
        depends_on:
            - lux_db
        environment:
            - ADMINER_DEFAULT_SERVER=lux_db
        networks:
            - lux_network

    lux_queue:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                ENVIRONMENT: development
                GROUP_ID: 1000
                USER_ID: 1000
        container_name: lux_queue
        depends_on:
            - lux_api
        volumes:
            - ./:/var/www/html
        networks:
            - lux_network
        command: php artisan queue:work --sleep=3 --tries=3

    lux_tests:
        build:
            context: .
            dockerfile: ./tests/Dockerfile
        container_name: lux_tests
        entrypoint: [ "./vendor/bin/phpunit" ]
        volumes:
            - .:/var/www/html
        depends_on:
            - lux_db

        networks:
            - lux_network
